= Create A Kubernetes Cluster
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images

This section will walk you through how to install a Kubernetes cluster on AWS China Ningxia region using kops.

== Usage for Mac and Linux

1. update your link:./env.config[env.config]

2. update your link:./create_cluster.sh[create cluster script], set your `vpcid` correctly and make sure `--ssh-public-key` points to your local SSH public key path. Update <iam_id> in cluster_name with your IAM user ID.

3. run the create script

    $ source env.config
    $ bash create_cluster.sh

4. Finally, update your cluster with `—yes`. This will apply the changes and create kops cluster on AWS. 

    $ kops update cluster cluster.zhy.k8s.local --yes

Typically it would take `3-5` minutes for the cluster to be created. You can use `kubectl get nodes` to check if all nodes are ready. 

== Usage for Windows

1. update your link:./create_cluster.bat[create cluster script], set your `vpcid` correctly and make sure `--ssh-public-key` points to your local SSH public key path. Update <iam_id> in cluster_name with your IAM user ID.

2. run the create script

    $ ./create_cluster.bat

3. Finally, update your cluster with `—yes`. This will apply the changes and create kops cluster on AWS. 

    $ kops update cluster cluster.zhy.k8s.local --yes

Typically it would take `3-5` minutes for the cluster to be created. You can use `kubectl get nodes` to check if all nodes are ready. 
