= Create A Kubernetes Cluster
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images

This section will walk you through how to install a Kubernetes cluster on AWS using kops.

= fastboot for NinXia(cn-northwest-1) region

All scripts for Kops fast bootstrapping in NinXia(cn-northwest-1) region.

== Usage

1. update your link:./env.config[env.config]

2. update your link:./create_cluster.sh[create cluster script], set your `vpcid` correctly and make sure `--ssh-public-key` points to your local SSH public key path. Update <iam_id> in cluster_name with your IAM user ID.

3. run the create script

```bash
$ bash create_cluster.sh
```

You will see message like this, please ignore it, as we are using an alternative `--kubernetes-version` specified in the `kops create cluster` and kops will consider this as an older version.


```bash
A new kubernetes version is available: 1.9.3
    Upgrading is recommended (try kops upgrade cluster)
    More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.9.3
```

4. Finally, update your cluster with `—yes`

```bash
 source ./env.config
 kops update cluster cluster.zhy.k8s.local --yes
```

When the master nodes under `ELB` become healthy, you may access your cluster with `kubectl`. Typically it would take `5-8` minutes to become all healthy.
