= Kubernetes - Setup Development Environment
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images


This section walks you through the creating a Kubernetes development environment using https://github.com/kubernetes/kops[kops].  

=== Using kops

=== Set up Environment

You need to install several tools to setup a Kubernetes enviornment. 

=== Configure the AWS CLI

Please following AWS document to install AWS CLI for your operation system. 
https://docs.aws.amazon.com/cli/latest/userguide/installing.html[AWS CLI Installation Guide]

After installation, you need to configure aws cli by executing 'aws configure'. Enter AK/SK for your AWS IAM user account. Set default region to 'cn-northwest-1'. 

    $ aws configure
    AWS Access Key ID [****************ZHVQ]:
    AWS Secret Access Key [****************eJr2]:
    Default region name [cn-northwest-1]:
    Default output format [json]:

=== Install Kubectl CLI

Install the Kubectl CLI on Windows: 

Download the installer and include it in your PATH. 

    https://s3.cn-northwest-1.amazonaws.com.cn/k8s-on-aws/kubectl.exe   

Install the Kubectl CLI on Mac: 

    $ brew install kubectl

Add kubectl autocompletion to your current shell:

    $ source <(kubectl completion bash)

You can verify that kubectl is installed by executing the following command:

    $ kubectl version --client
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

=== Install kops

Install kops using the following on Windows: 

Download the binary, rename it to kops.exe and include it in your PATH.

    https://s3.cn-northwest-1.amazonaws.com.cn/k8s-on-aws/kops-windows-amd64 


Install kops using the following on Mac:

    $ brew install kops

You can verify the kops works by executing the following command: 

    $ kops version
    Version 1.10.0


=== Collect Availability Zones

kops needs to know the availability zones to use when configuring a cluster. We set an environment variable `$AWS_AVAILABILITY_ZONES` based on the region.

    $ export AWS_AVAILABILITY_ZONES="$(aws ec2 describe-availability-zones --query 'AvailabilityZones[].ZoneName' --output text | awk -v OFS="," '$1=$1')"

=== Configure an S3 bucket for kops

kops needs a "`state store`" to store configuration information of the cluster. We will use a s3 bucket with versioning enabled. A state store can work with multiple kops clusters.

[NOTE]
The bucket name must be unique otherwise you will encounter an error on deployment. We will use an example bucket name of `kops-state-store-` and add your IAM user ID

    $ export IAM-ID=<your iam user id>
    $ export S3_BUCKET=kops-state-store-${IAM-ID}
    $ export KOPS_STATE_STORE=s3://${S3_BUCKET}
    $ aws s3 mb $KOPS_STATE_STORE
    $ aws s3api put-bucket-versioning --bucket $S3_BUCKET --versioning-configuration Status=Enabled

=== Clone the repository

The workshop repository has configuration files that are used to create Kubernetes resources.  You need to clone the repo to have access to those files:

    $ git clone https://github.com/bnusunny/aws-workshop-for-kubernetes

At this point, you should have everything you need to complete any of the sections of the this workshop.

====
